services:
  # nginx
  web:
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./docker-containers/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    build:
      dockerfile: ./docker-containers/php/DockerFile
    volumes:
      - ./app:/app

  # mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin@os2221
      MYSQL_USER: os_admin
      MYSQL_PASSWORD: admin@os2221
      MYSQL_DATABASE: db_online_shopping
    
  # redis  

volumes:
  mysqldata: